# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 25ee95e48da2a9174281fca0b0cadecedd6c02ab2f0408f2d70d446f5135d7c0ee7fe0d6ec8e4cce0333975b6df144cffdc69731e645e728b63cfee0de7c1829

test:
  secret_key_base: c139825d9c0888f31fc4b6c1ef0da564fdcc58449c1b649621b3e8e0c21cba28685d54cc4e93ec9f4e288c94c13f113ae4dc64ab3cdc114b1e2f59d7ab0b2210

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
